sudo: required
language: cpp
dist: trusty
group: edge

compiler:
    - gcc
os:
    - linux


notifications:
  email: false

services:
  docker

# Blacklist
branches:
  only:
     - master

before_install:
  - env
  - docker pull rthrh/imflow
  - export ci_env=`bash <(curl -s https://codecov.io/env)`


script:
  - echo "start travis script"
  - export CC=gcc-6 CXX=g++-6 CMAKE_BUILD_TYPE=Debug
  - chmod +x .script_travis.sh
  - ./.script_travis.sh


after_success:
  # Creating report
  #- cd ${TRAVIS_BUILD_DIR}
  #- lcov --directory . --capture --output-file coverage.info # capture coverage info
  #- lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  #- lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  #- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
